services:
  # --- INSTANCE ---
  backend:
    build: ./services/backend
    depends_on:
      db: { condition: service_healthy }
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME

  # --- INFRASTRUCTURE ---
  db:
    build: ./services/db
    volumes:
      - ./volumes/db/data:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
